# Generated by Django 5.2.6 on 2025-10-07 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='desciption',
            new_name='description',
        ),
    ]
